GET http://127.0.0.1:3001/api/people
###

@id = 68f765b36b53fbe74af18be1
DELETE http://127.0.0.1:3001/api/people/{{id}}
###

POST http://127.0.0.1:3001/api/people
content-type: application/json

{
  "name": "Vera Hustles",
  "number": "2024-208834058"
}
